spring.application.name=cartzilla

spring.datasource.url=jdbc:postgresql://localhost:5432/cartzilla
spring.datasource.username=admin
spring.datasource.password=postgresql-admin1$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
